package com.example.romanovsky_m.gifsearcher.DataBase;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.romanovsky_m.gifsearcher.DataBase.LikedGifData;

import com.example.romanovsky_m.gifsearcher.DataBase.LikedGifDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig likedGifDataDaoConfig;

    private final LikedGifDataDao likedGifDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        likedGifDataDaoConfig = daoConfigMap.get(LikedGifDataDao.class).clone();
        likedGifDataDaoConfig.initIdentityScope(type);

        likedGifDataDao = new LikedGifDataDao(likedGifDataDaoConfig, this);

        registerDao(LikedGifData.class, likedGifDataDao);
    }
    
    public void clear() {
        likedGifDataDaoConfig.clearIdentityScope();
    }

    public LikedGifDataDao getLikedGifDataDao() {
        return likedGifDataDao;
    }

}
